language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      services:
        - docker
      env: DOCKERFILE="debian-stretch" JOBS=4


install:
  - if [ -n "$DOCKERFILE" ]; then
      ./script/docker-build.sh "$DOCKERFILE";
    fi

script:
  - if [ -n "$DOCKERFILE" ]; then
      ./script/docker-make.sh "$DOCKERFILE";
    fi
